/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PoolGame;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;

import PoolGame.Cheat.CheatBall;
import PoolGame.GameState.EasyState;
import PoolGame.GameState.HardState;
import PoolGame.GameState.NormalState;
import PoolGame.GameState.StateContext;
import PoolGame.Items.PoolTable;
import PoolGame.Memento.Caretaker;
import PoolGame.Memento.Memento;
import javafx.event.EventHandler;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import org.json.simple.parser.ParseException;

import PoolGame.ConfigReader.ConfigKeyMissingException;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.stage.Stage;
import javafx.util.Duration;
import javafx.scene.text.*;

/** The JavaFX application */
public class App extends Application {

    private final double FRAMETIME = 1.0 / 60.0;
    Caretaker ct = new Caretaker();

    private ConfigReader loadConfig(List<String> args) {
        String configPath;
        boolean isResourcesDir = false;
		if (args.size() > 0) {
			configPath = args.get(0);
		} else {
			// configPath = "src/main/resources/config.json";
			configPath = "/config_easy.json";
            isResourcesDir = true;
		}
		// parse the file:
        ConfigReader config = null;
        try {
            config = new ConfigReader(configPath, isResourcesDir);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.err.printf("ERROR: %s\n", e.getMessage());
            System.exit(1);
        } catch (IOException e) {
            e.printStackTrace();
            System.err.printf("ERROR: %s\n", e.getMessage());
            System.exit(1);
        } catch (ParseException e) {
            e.printStackTrace();
            System.err.printf("ERROR: %s\n", e.getMessage());
            System.exit(1);
        } catch (ConfigKeyMissingException e) {
            e.printStackTrace();
            System.err.printf("ERROR: %s\n", e.getMessage());
            System.exit(1);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
            System.err.printf("ERROR: %s\n", e.getMessage());
            System.exit(1);
        }
        return config;
    }

    @Override
    public void start(Stage stage) {
        Group root = new Group();
        Scene scene = new Scene(root);

        stage.setScene(scene);
        stage.setTitle("PoolGame");
        stage.show();

        ConfigReader config = loadConfig(getParameters().getRaw());
        Game game = new Game(config);

        Canvas canvas = new Canvas(game.getWindowDimX(), game.getWindowDimY());

        stage.setWidth(game.getWindowDimX() + 14 + game.getWindowDimX()/3);
        stage.setHeight(game.getWindowDimY() +
                game.getPoolTable().POCKET_OFFSET +
                PoolTable.POCKET_OFFSET + 26); // Magic number to get bottom to align
        //For placing timers, scorers, level switches

        root.getChildren().add(canvas);
        // GraphicsContext gc = canvas.getGraphicsContext2D();
        game.addDrawables(root);

        Timeline timeline = new Timeline();
        timeline.setCycleCount(Timeline.INDEFINITE);

        //Time
        Label timeCounter = new Label();
        timeCounter.setLayoutX(game.getWindowDimX() + 14);
        timeCounter.setLayoutY(100);
        root.getChildren().add(timeCounter);

        //Score
        Label scoreCounter = new Label();
        scoreCounter.setLayoutX(game.getWindowDimX() + 14);
        scoreCounter.setLayoutY(150);
        root.getChildren().add(scoreCounter);

        KeyFrame frame = new KeyFrame(Duration.seconds(FRAMETIME),
                (actionEvent) -> {
                    game.tick();
                    timeCounter.setText("Time: " + game.getTimeString());
                    scoreCounter.setText("Score: " + game.getScoreString());

                });

        timeline.getKeyFrames().add(frame);
        timeline.play();

        //button for cheat
        CheatBall cheatBall = new CheatBall(game);
        cheatBall.getCheatButton(root);

        //button for levels
        Button buttonEasy = new Button("Easy");
        Button buttonNormal = new Button("Normal");
        Button buttonHard = new Button("Hard");

        buttonEasy.setLayoutX(game.getWindowDimX() + 14);
        buttonEasy.setLayoutY(25);
        buttonNormal.setLayoutX(game.getWindowDimX() + 64);
        buttonNormal.setLayoutY(25);
        buttonHard.setLayoutX(game.getWindowDimX() + 129);
        buttonHard.setLayoutY(25);

        Text t = new Text(game.getWindowDimX() + 14, 15, "Select the level please.");
        root.getChildren().add(buttonEasy);
        root.getChildren().add(buttonNormal);
        root.getChildren().add(buttonHard);
        root.getChildren().add(t);


        Text levelText = new Text(game.getWindowDimX() + 14, 65, "Now Level: default/customize");
        root.getChildren().add(levelText);

        buttonEasy.setOnMouseClicked(new EventHandler<MouseEvent>() {
            @Override
            public void handle(MouseEvent event) {
                System.out.println("Easy");

                StateContext stateContext = new StateContext();
                EasyState easyState = new EasyState();
                stage.setScene(easyState.handle(stateContext, stage, FRAMETIME));
            }
        });
        buttonNormal.setOnMouseClicked(new EventHandler<MouseEvent>() {
            @Override
            public void handle(MouseEvent event) {
                System.out.println("Normal");

                StateContext stateContext = new StateContext();
                NormalState normalState = new NormalState();
                stage.setScene(normalState.handle(stateContext, stage, FRAMETIME));
            }
        });
        buttonHard.setOnMouseClicked(new EventHandler<MouseEvent>() {
            @Override
            public void handle(MouseEvent event) {
                System.out.println("Hard");

                StateContext stateContext = new StateContext();
                HardState hardState = new HardState();
                stage.setScene(hardState.handle(stateContext, stage, FRAMETIME));
            }
        });

        //Recover
        Button buttonRecover = new Button("Recover to the last state");
        buttonRecover.setLayoutX(game.getWindowDimX() + 14);
        buttonRecover.setLayoutY(game.getWindowDimY()-50);

        root.getChildren().add(buttonRecover);


        ct.setMemento(game.saveStateAction());
        buttonRecover.setOnMouseClicked(new EventHandler<MouseEvent>() {
            @Override
            public void handle(MouseEvent event) {
                ct.setMemento(game.saveStateAction());
                game.undoAction(root, ct.getMemento(), cheatBall);
            }
        });
    }

    /**
     * The entry point of the program
     * @param args CLI arguments
     */
    public static void main(String[] args) {
        launch(args);
    }
}